version: '3.7'

services:
  web:
    container_name: postal_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/web'
      - '/web/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true