version: '3.7'

services:
  server:
    container_name: postal_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/home/app'
    ports:
      - 8080:8080
  web:
    container_name: postal_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/web'
      - '/web/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true